# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"kcred": "extract.ipynb",
         "unzip": "extract.ipynb",
         "download_kaggle_dataset": "extract.ipynb"}

modules = ["loader.py"]

doc_url = "https://talosiot-will.github.io/agora/"

git_url = "https://github.com/talosiot-will/agora/tree/master/"

def custom_doc_links(name): return None
